version: "3.8"

services:
  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: food-ordering-db
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - ./backend/src/main/resources/db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  # Serviço da Aplicação Backend
  backend:
    build: ./backend
    container_name: food-ordering-app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: ./.env
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - STRIPE_URL=${STRIPE_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_FULLNAME=${ADMIN_FULLNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

volumes:
  mysql-data:
