export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE";

export const GET_CHAT_MESSAGES_REQUEST = "GET_CHAT_MESSAGES_REQUEST";
export const GET_CHAT_MESSAGES_SUCCESS = "GET_CHAT_MESSAGES_SUCCESS";
export const GET_CHAT_MESSAGES_FAILURE = "GET_CHAT_MESSAGES_FAILURE";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const GET_USERS_CHATS_REQUEST = "GET_USERS_CHATS_REQUEST";
export const GET_USERS_CHATS_SUCCESS = "GET_USERS_CHATS_SUCCESS";
export const GET_USERS_CHATS_FAILURE = "GET_USERS_CHATS_FAILURE";

export const GET_RESTAURANTS_CHATS_REQUEST = "GET_RESTAURANTS_CHATS_REQUEST";
export const GET_RESTAURANTS_CHATS_SUCCESS = "GET_RESTAURANTS_CHATS_SUCCESS";
export const GET_RESTAURANTS_CHATS_FAILURE = "GET_RESTAURANTS_CHATS_FAILURE";
