export const GET_ALL_RESTAURANTS_ADMIN_REQUEST =
  "GET_ALL_RESTAURANTS_ADMIN_REQUEST";
export const GET_ALL_RESTAURANTS_ADMIN_SUCCESS =
  "GET_ALL_RESTAURANTS_ADMIN_SUCCESS";
export const GET_ALL_RESTAURANTS_ADMIN_FAILURE =
  "GET_ALL_RESTAURANTS_ADMIN_FAILURE";

export const APPROVE_RESTAURANT_REQUEST = "APPROVE_RESTAURANT_REQUEST";
export const APPROVE_RESTAURANT_SUCCESS = "APPROVE_RESTAURANT_SUCCESS";
export const APPROVE_RESTAURANT_FAILURE = "APPROVE_RESTAURANT_FAILURE";
