export const GET_RESTAURANT_REVIEWS_REQUEST = "GET_RESTAURANT_REVIEWS_REQUEST";
export const GET_RESTAURANT_REVIEWS_SUCCESS = "GET_RESTAURANT_REVIEWS_SUCCESS";
export const GET_RESTAURANT_REVIEWS_FAILURE = "GET_RESTAURANT_REVIEWS_FAILURE";

export const SUBMIT_REVIEW_REQUEST = "SUBMIT_REVIEW_REQUEST";
export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS";
export const SUBMIT_REVIEW_FAILURE = "SUBMIT_REVIEW_FAILURE";
